include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - file_size_signal:
      max_lines: 30
    - avoid_raw_string_in_widgets:
      targets:
        AppButton: [label]
        TerminalAppBar: [title]
    - avoid_widget_returning_methods
    - models_are_dtos
